export const MovieGenres = {
  28: "Action",
  12: "Adventure",
  16: "Animation",
  35: "Comedy",
  80: "Crime",
  99: "Documentary",
  18: "Drama",
  10751: "Family",
  14: "Fantasy",
  36: "History",
  27: "Horror",
  10402: "Music",
  9648: "Mystery",
  10749: "Romance",
  878: "Science Fiction",
  10770: "TV Movie",
  53: "Thriller",
  10752: "War",
  37: "Western",
  10759: "Action & Adventure",
  16: "Animation",
  35: "Comedy",
  80: "Crime",
  99: "Documentary",
  18: "Drama",
  10751: "Family",
  10762: "Kids",
  9648: "Mystery",
  10763: "News",
  10764: "Reality",
  10765: "Sci-Fi & Fantasy",
  10766: "Soap",
  10767: "Talk",
  10768: "War & Politics",
  37: "Western",
};

export const MovieUrls = [
  "https://endflix-seeds.s3.amazonaws.com/shangchi2.mp4",
  "https://endflix-seeds.s3.amazonaws.com/Batman.mp4",
  "https://endflix-seeds.s3.amazonaws.com/SNWH.mp4",
  "https://endflix-seeds.s3.amazonaws.com/HathAway.mp4",
  "https://endflix-seeds.s3.amazonaws.com/VLTBC.mp4",
  "https://endflix-seeds.s3.amazonaws.com/Acana.mp4",
  "https://endflix-seeds.s3.amazonaws.com/MugenTrain.mp4",
  "https://endflix-seeds.s3.amazonaws.com/AOTmp4.mp4",
  "https://endflix-seeds.s3.amazonaws.com/SpiritedAway.mp4",
  "https://endflix-seeds.s3.amazonaws.com/Howls.mp4",
  "https://endflix-seeds.s3.amazonaws.com/VE.mp4",
  "https://endflix-seeds.s3.amazonaws.com/PrincessMono.mp4",
  "https://endflix-seeds.s3.amazonaws.com/Vincenzo.mp4",
  "https://endflix-seeds.s3.amazonaws.com/SquidGame.mp4",
  "https://endflix-seeds.s3.amazonaws.com/WYWS.mp4",
];
