export const MovieApiKeys = import.meta.env.VITE_REACT_APP_TMDBAPIKEY;

export const MovieEndpoints = {
  popular: `https://api.themoviedb.org/3/tv/popular?api_key=${MovieApiKeys}&language=en-US&page=1`,
  top_rated: `https://api.themoviedb.org/3/tv/top_rated?api_key=${MovieApiKeys}&language=en-US&page=1`,
  upcoming: `https://api.themoviedb.org/3/movie/upcoming?api_key=${MovieApiKeys}&language=en-US&page=1`,
  now_playing: `https://api.themoviedb.org/3/movie/now_playing?api_key=${MovieApiKeys}&language=en-US&page=1`,
  search: `https://api.themoviedb.org/3/search/movie?api_key=${MovieApiKeys}&language=en-US&query=`,
  popularTv: `https://api.themoviedb.org/3/tv/popular?api_key=${MovieApiKeys}&language=en-US&page=1`,
  Animations: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_genres=16`,
  NetFlixOriginals: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&page=1&timezone=America%2FNew_York&with_networks=213`,
  Action: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_genres=10759`,
  Comedy: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_genres=35`,
  Horror: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_genres=27`,
  Romance: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_genres=10749`,
  Documentaries: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_genres=99`,
  Fantasy: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_genres=10765`,
  Family: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_genres=10751`,
  Mystery: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_genres=9648`,
  SciFi: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_genres=10765`,
  Thriller: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_genres=53`,
  War: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_genres=10752`,
  Western: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_genres=37`,
  Crime: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_genres=80`,
  Drama: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_genres=18`,
  Music: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_genres=10402`,
  History: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_genres=36`,
  Adventure: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_genres=12`,
  ActionMovies: `https://api.themoviedb.org/3/discover/movie?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_genres=28`,
  ComedyMovies: `https://api.themoviedb.org/3/discover/movie?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_genres=35`,
  HorrorMovies: `https://api.themoviedb.org/3/discover/movie?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_genres=27`,
  RomanceMovies: `https://api.themoviedb.org/3/discover/movie?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_genres=10749`,
  DocumentariesMovies: `https://api.themoviedb.org/3/discover/movie?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_genres=99`,
  FantasyMovies: `https://api.themoviedb.org/3/discover/movie?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_genres=14`,
  FamilyMovies: `https://api.themoviedb.org/3/discover/movie?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_genres=10751`,
  MysteryMovies: `https://api.themoviedb.org/3/discover/movie?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_genres=9648`,
  SciFiMovies: `https://api.themoviedb.org/3/discover/movie?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_genres=878`,
  ThrillerMovies: `https://api.themoviedb.org/3/discover/movie?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_genres=53`,
  WarMovies: `https://api.themoviedb.org/3/discover/movie?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_genres=10752`,
  WesternMovies: `https://api.themoviedb.org/3/discover/movie?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_genres=37`,
  CrimeMovies: `https://api.themoviedb.org/3/discover/movie?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=1&with_genres=80`,
  DramaMovies: `https://api.themoviedb.org/3/discover/movie?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&page=2&with_genres=18`,
  MusicMovies: `https://api.themoviedb.org/3/discover/movie?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&include_adult=true&include_video=false&page=1&with_genres=10402`,
  HistoryMovies: `https://api.themoviedb.org/3/discover/movie?api_key=${MovieApiKeys}&language=en-US&sort_by=popularity.desc&include_adult=true&include_video=false&page=1&with_genres=36`,
  KDrama: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_original_language=ko`,
  Anime: `https://api.themoviedb.org/3/discover/tv?api_key=${MovieApiKeys}&sort_by=popularity.desc&with_original_language=ja&with_genres=16`,
};
// https://api.themoviedb.org/3/search/tv?api_key=057e037396b3e44f631f913549e9891d&query=Vincenzo
