"""empty message

Revision ID: 5030e7f69ccd
Revises: 0c4149e27046
Create Date: 2023-03-03 01:55:25.158980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5030e7f69ccd'
down_revision = '0c4149e27046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
