"""empty message

Revision ID: 5b823db8d06c
Revises: c1b623c16b4a
Create Date: 2023-02-27 16:14:12.470430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b823db8d06c'
down_revision = 'c1b623c16b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('videos', sa.JSON(), nullable=False))
        batch_op.create_unique_constraint(None, ['profile_id'])
        batch_op.drop_constraint('lists_video_id_fkey', type_='foreignkey')
        batch_op.drop_column('video_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('lists_video_id_fkey', 'videos', ['video_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('videos')

    # ### end Alembic commands ###
